name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Execute remote SSH commands
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "${SSH_PRIVATE_KEY}" > id_rsa
        chmod 600 id_rsa
        ssh -o StrictHostKeyChecking=no -i id_rsa ubuntu@ec2-18-208-198-197.compute-1.amazonaws.com << 'EOF'
        rm -rf ABI-Assesment-React
        git clone https://github.com/HodHod106/ABI-Assesment-React.git
        cd ABI-Assesment-React
        npm install
        npm start &
        EOF

